projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      endpoint:
        default:
          url: https://us1.prisma.sh/raj-singh/depsauce/dev
          headers:
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDcwMDUxOTEsIm5iZiI6MTU0NjkxODc5MX0.lA4bkELOgvRu4nvzul4df46VfihjiY9oOSQjJ3tIbNY
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
